version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose up -d ci
      - run: docker-compose exec ci pnpm e2e

workflows:
  workflow:
    jobs:
      - test
